In [2]:
import numpy as np
import pickle
import matplotlib.pyplot as plt

# 2 La boîte à outils mathématiques : numpy

## Exercice 1

In [ ]:
a = np.array([1,2,3])
type(a)

In [ ]:
a.shape

In [3]:
b = np.array([[1,2],[8,13]])
b.shape

(2, 2)

In [4]:
a = np.zeros((5,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
b = np.ones((2,3))
b

In [ ]:
(n,m) = b.shape
n,m

In [ ]:
c = np.arange(start=3,stop=10,step=0.5)
c

In [5]:
a = np.arange(0,5)
a

array([0, 1, 2, 3, 4])

In [ ]:
np.exp(a)

In [ ]:
10**a

In [6]:
a = np.random.random((4,5))
a

array([[0.15612644, 0.72254881, 0.47273212, 0.11044214, 0.63742877],
       [0.2572823 , 0.54757938, 0.40321018, 0.02615522, 0.05053117],
       [0.21617175, 0.63672891, 0.61447471, 0.38070736, 0.02559262],
       [0.16860591, 0.75233839, 0.60157713, 0.36360828, 0.33466388]])

In [ ]:
b = np.ones((4,5))
a + b

In [ ]:
sum(b)

In [ ]:
a.min()

In [ ]:
c = a.sum(1)
c

In [ ]:
d = a[:,1:3]
d

In [ ]:
b = np.copy(a)

In [ ]:
def carre(x):
    return x**2
carre

In [ ]:
carre(2)

In [ ]:
carre = carre(2)
carre

In [ ]:
carre(2)

In [ ]:
l = [1,2,3]
type(l)

In [ ]:
l = np.array(l)
type(l)

In [ ]:
l = list(l)
type(l)

# 3 Ouvrir et écrire dans des fichiers avec pickle

In [ ]:
f = open("premierfichier.txt", "wb")
x = np.random.random((10,10))
pickle.dump(x,f)
f.close()

In [ ]:
x

In [ ]:
f = open("premierfichier.txt", "rb")
y = pickle.load(f)
f.close()

In [ ]:
y

In [ ]:
np.all(x == y)

## Exercice 2

In [ ]:
f = open('pop2011.txt', 'rb')
x = pickle.load(f)
f.close()
x

In [ ]:
with open('pop2011.txt', 'rb') as f:
    x = pickle.load(f)
x

In [ ]:
x.sum() / x.shape[0]

# 4 Réaliser des graphes avec matplotlib.pyplot

In [ ]:
plt.plot([3,1,3,1,2])
plt.ylabel("ordonnées")
plt.xlabel("abscisses")
plt.show()

In [ ]:
plt.plot([1,3,2,4],[1,4,9,16])
plt.show()

In [ ]:
plt.figure(2,figsize=(6,4))
t = np.arange(0,6.2,0.1)
plt.plot(t,np.cos(t),color="red",label="cosinus")
plt.plot(t,np.sin(t),color="black",label="sinus")
plt.xlabel("abscisses")
plt.ylabel("ordonnées")
plt.title("Représentation graphique des fonctions sinusoïdales")
plt.legend() 
plt.show()

## Exercice 3

In [ ]:
x = np.arange(-1,2,0.01)
y = x**2
plt.figure(1)
plt.plot(x,y, color="black", label="x^2")
plt.plot(x, 2*x-1, "red", linestyle="dashed", label="tangente en x=1")
plt.xlabel("abscisses")
plt.ylabel("ordonnées")
plt.title("Représentation graphique de la fonction carré et sa tangente en x=1")
plt.legend()
plt.show()

In [ ]:
val_x = [0,1,2,3,4,5,6,7]
eff_x = [5,7,8,4,2,2,1,1]
plt.bar(val_x, eff_x, width=0.5, color=["red","blue","black","green","yellow"])
plt.xlabel("Nombre d’enfants")
plt.ylabel("Effectifs")
plt.title("Nombre d’enfants par familles")
plt.show()

## Exercice 4

In [ ]:
region = ['Africa', 'Americas', 'South-East\n Asia', 'Europe', 'Eastern\n Mediterranean', 'Western\n Pacific']
esperance = [60.0, 76.9, 69.0, 76.8, 68.8, 76.6]
colors = ['black', 'red', 'green', 'blue', 'orange', 'yellow']
plt.bar(region, esperance, color=colors)
plt.ylabel('espérance de vie')
plt.title('Espérance de vie à la naissance en fonction des régions du monde')
plt.show()

In [ ]:
x = [44,62,71,73,87]
y = [40,57,59,65,77]
plt.scatter(x,y)
plt.xlabel("Longueur de l'humérus en cm")
plt.ylabel("Longeur du fémur en cm")
plt.title("Longueur du fémur en fonction de celle de l'humérus")
plt.show()

## Exercice 5

In [ ]:
f = open('kangourou.txt', 'rb')
tab = pickle.load(f)
f.close()
tab

In [ ]:
with open('kangourou.txt', 'rb') as f:
    tab = pickle.load(f)
tab

In [ ]:
plt.scatter(tab[:,0], tab[:,1])
plt.xlabel("Longeur (1 unité = 0.1mm)")
plt.ylabel("Largeur (1 unité = 0.1mm)")
plt.title("Taille du nez des kangourous")
plt.show()

In [ ]:
val_x = [0,1,2,3,4,5,6,7]
eff_x = [5,7,8,4,2,2,1,1]
fig = plt.figure(figsize=[6,6])
plt.pie(eff_x, labels=val_x, colors=["red", "blue", "yellow", "green"], autopct=lambda x:str(round(x,2)) + "%", pctdistance=0.7)
plt.title("Nombre d'enfants par familles")
plt.show()

## Exercice 6

In [ ]:
x = [314, 100, 47, 35, 31, 17, 16, 16]
labels = ['La république en marche', 'Les Républicains', 'Mouvement démocrate et apparentés', 'Les constructifs : républicains, UDI, indépendants', 
          'Nouvelle Gauche', 'La France Insoumise', 'Gauche démocrate et républicaine ', 'Non inscrit']
colors = ['gold', 'darkturquoise', 'cyan', 'orange', 'deeppink', 'darkred', 'red', 'grey']
plt.figure(1, figsize=(10, 10))
plt.pie(x, labels=labels, autopct=lambda x:str(round(x,2)) + '%', pctdistance=0.8, colors=colors)
plt.title('Assemblée parlementaire')
plt.show()

In [ ]:
plt.figure(1, figsize=(30, 6))
plt.bar(labels, x, color=colors)
plt.xlabel("Groupes parlementaires")
plt.ylabel("Nombre de députés")
plt.title("Nombre de députés de chaque groupe parlementaire")
plt.show()

Les groupes parlementaires représentent un partage d'un tout (l'assemblée), il est donc plus pertinent de les représenter sous forme de diagramme circulaire.

In [ ]:
y = [150]*30 + [157.5]*25 + [162.5]*23 + [170]*22
plt.hist(y, density=True, bins=[145,155,160,165,175], edgecolor="black")
plt.xlabel("Taille en cm")
plt.title("Histogramme de la taille des collégiens")
plt.show()

## Exercice 7

In [ ]:
mu = 100
sigma = 15 
x = mu + sigma*np.random.randn(1000)
num_bins = 50
n, bins, patches = plt.hist(x, num_bins)
plt.xlabel('Valeur')
plt.ylabel('Probabilite')
plt.title("Histogramme d'une loi gaussienne : μ= 100,σ= 15") 
plt.show()

## Exercice 8

In [ ]:
academie = ['Aix-Marseille', 'Amiens', 'Besançon', 'Bordeaux', 'Caen', 'Clermont-Ferrand', 'Corse', 'Créteil']
inscrits = [3732, 1661, 1103, 4270, 1384, 1455, 337, 4953]
presents = [1496, 770, 484, 1632, 602, 453, 122, 1757]
admissibles = [897, 567, 320, 784, 349, 217, 39, 1390]
admis = [559, 435, 195, 382, 174, 110, 16, 1111]

In [ ]:
x = range(1,len(academie) + 1)
fig = plt.figure(1, figsize=(10, 5))
plt.bar(x, inscrits, color='grey')
plt.bar(x, presents, color='blue')
plt.bar(x, admissibles, color='red')
plt.bar(x, admis, color='black')
plt.title('Données concours recrutement professuers des écoles')
plt.xticks(x,academie)
plt.show()

In [ ]:
x = np.array(range(1,len(academie) + 1))
barwidth = 0.2
fig = plt.figure(1, figsize=(10, 5))
plt.bar(x, inscrits, color='grey', width=barwidth, label='Inscrits')
plt.bar(x + barwidth, presents, color='blue', width=barwidth, label='Présents')
plt.bar(x + 2*barwidth, admissibles, color='red', width=barwidth, label='Admissibles')
plt.bar(x + 3*barwidth, admis, color='black', width=barwidth, label='Admis')
plt.title('Données concours recrutement professuers des écoles')
plt.xticks(np.array(x) + 1.5*barwidth,academie)
plt.legend()
plt.show()